# Site Configuration
# Edit this file to update site-wide settings

site:
  title: Lulu Tracy
  description: Art portfolio of Lulu Tracy - exploring nature through watercolors and acrylics
  author: Lulu Tracy
  url: https://alexnodeland.github.io/lulutracy.com
  copyright: "Copyright {year} lulutracy. All rights reserved."

navigation:
  - label: about
    path: /about

social:
  # Add social media links here
  # - platform: instagram
  #   url: https://instagram.com/lulutracy
