# Site Configuration
# Invariant data only - translations live in locales/*/common.json

site:
  name: lulutracy
  author: Tracy Mah
  email: tracy@lulutracy.com
  url: https://our-nature.github.io/lulutracy.com
